databases:
  - name: postgres
    databaseName: nice_car_app
    user: nice_car_user

services:
  - type: web
    name: nice_car_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false